[package]
name = "solve_ivp_bdf"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A simple port of the solve_ivp BDF method from Scipy."

[dependencies]
anyhow = "1.0.98"
nalgebra = "0.33.2"
thiserror = "2.0.12"
